/**
 * Conversion node component.
 *
 * Auto-inserted by `flowStore.onConnect` when the user connects two pins
 * of different but compatible data types (e.g., float output → string input).
 *
 * The conversion node has exactly one input pin and one output pin,
 * showing the source and target types. The label (e.g., "Float → String")
 * is generated by `getConversionLabel()` in conversionUtils.ts.
 *
 * During execution, the executor recognizes nodes with `category: 'conversion'`
 * and calls `convertValue()` to transform the input.
 *
 * This is a custom renderer because conversion nodes have a minimal layout —
 * just a header with the conversion label and a single input/output row.
 * No inline value editor is needed (the conversion is implicit).
 */
import { type NodeProps, Position } from '@xyflow/react';
import type { BlueprintNodeData } from '../types';
import { DataPin } from '../pins/DataPin';
import { NodeIcon } from '../components/NodeIcon';
import { useExecutionStore } from '../store/executionStore';
import './BaseNode.css';

export function ConversionNode({ id, data }: NodeProps) {
  const { label, inputs = [], outputs = [] } = data as BlueprintNodeData;
  const activeNodeId = useExecutionStore((s) => s.activeNodeId);
  const isActive = activeNodeId === id;
  const inputType = inputs[0]?.dataType;
  const outputType = outputs[0]?.dataType;

  return (
    <div className={`blueprint-node ${isActive ? 'blueprint-node--executing' : ''}`} style={{ '--header-color': '#2a4a6b' } as React.CSSProperties}>
      <div className="blueprint-node__header">
        <span className="blueprint-node__header-icon">
          <NodeIcon category="conversion" />
        </span>
        <span className="blueprint-node__header-label">{label}</span>
      </div>
      <div className="blueprint-node__body">
        <div className="blueprint-node__row">
          <div className="blueprint-node__pin-group">
            {inputType && <DataPin id={inputs[0].id} type="target" dataType={inputType} position={Position.Left} />}
          </div>
          <div className="blueprint-node__pin-group blueprint-node__pin-group--right">
            {outputType && <DataPin id={outputs[0].id} type="source" dataType={outputType} position={Position.Right} />}
          </div>
        </div>
      </div>
    </div>
  );
}
